# Basic Information 
title: Patrick Godau
position: Postdoctoral Researcher
affiliation: German Cancer Research Center
email: patrick.godau (at) dkfz-heidelberg.de

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: data science, machine learning, image processing
description: Patrick Godau's academic personal homepage.
canonical: https://godaup.github.io

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=VRcPeykAAAAJ
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/godaup
institute: https://www.dkfz.de/en/employees/patrick-godau
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - README.md
  - LICENSE
